
```{r loading packages}
library(tidyverse)
library(lubridate) #dates
library(hms) #time
library(data.table) #exporting data frame
```

```{r loading data}
# loading data from January 2023 to November 2023 
jan_23 <- read.csv("202301-divvy-tripdata.csv")
feb_23 <- read.csv("202302-divvy-tripdata.csv")
mar_23 <- read.csv("202303-divvy-tripdata.csv")
apr_23 <- read.csv("202304-divvy-tripdata.csv")
may_23 <- read.csv("202305-divvy-tripdata.csv")
jun_23 <- read.csv("202306-divvy-tripdata.csv")
jul_23 <- read.csv("202307-divvy-tripdata.csv")
aug_23 <- read.csv("202308-divvy-tripdata.csv")
sep_23 <- read.csv("202309-divvy-tripdata.csv")
oct_23 <- read.csv("202310-divvy-tripdata.csv")
nov_23 <- read.csv("202311-divvy-tripdata.csv")

# merge all data frames into a year view 

cyclistic_2023 <- rbind(jan_23,feb_23,mar_23,apr_23,may_23,jun_23,jul_23,aug_23,sep_23,oct_23,nov_23)

# removing months from the environment to clean space

remove(jan_23,feb_23,mar_23,apr_23,may_23,jun_23,jul_23,aug_23,sep_23,oct_23,nov_23)

# create a new data frame for statistical analysis
cycledata <- cyclistic_2023

```

```{r columns and cleaning}

# changing the started_at and ended_at variables from characters to date-tme

cycledata$started_at = strptime(cycledata$started_at, "%Y-%m-%d %H:%M:%S")
cycledata$ended_at = strptime(cycledata$ended_at, "%Y-%m-%d %H:%M:%S")

# I added new columns for day, day_of_week, and month. https://www.r-bloggers.com/2013/08/date-formats-in-r/
  
cycledata$date <- as.Date(cycledata$started_at)
cycledata$day <- format(as.Date(cycledata$date), "%d") # new column of day
cycledata$month <- format(as.Date(cycledata$date), "%m") # new column of month 
cycledata$day_of_week <- format(as.Date(cycledata$date), "%A") # new column of day of week

# created a column called ride_length that is the difference of ended_at and started_at in seconds 

cycledata$ride_length <- difftime(cycledata$ended_at, cycledata$started_at)

str(cycledata)
summary(cycledata) #statistical summary of the data

# create columns for the different season in the year

cycledata <- cycledata |> 
  mutate(quarter = 
           case_when(month == "03" ~ "Spring",
                     month == "04" ~ "Spring",
                     month == "05" ~ "Spring",
                     month == "06" ~ "Summer",
                     month == "07" ~ "Summer",
                     month == "08" ~ "Summer",
                     month == "09" ~ "Autumn",
                     month == "10" ~ "Autumn",
                     month == "11" ~ "Autumn",
                     month == "12" ~ "Winter",
                     month == "01" ~ "Winter",
                     month == "02" ~ "Winter"))


# removed columns not being used in my final analysis 
cycledata <- cycledata |> 
  select(-c(ride_id,start_station_name,start_station_id,end_station_name,end_station_id,start_lat,start_lng,end_lat,end_lng))

# renamed the column member_casual to membership
cycledata <- cycledata |> 
  rename("membership" = "member_casual")

# final data cleaning
cycledata <- cycledata |> 
  filter(ride_length>0) # removing ride lengths less than 0
cycledata <- distinct(cycledata) # removing duplicate rows
cycledata <- na.omit(cycledata) # removing NA values

```

```{r analysis}

cycle_sum <- cycledata |> 
  group_by(membership) |> 
  summarise(mean_ride = mean(ride_length),
            min_ride = min(ride_length),
            max_ride = max(ride_length))

tibble(cycle_sum) # looking at the mean, min, and max ride length of casual vs annual members

# On average, casual members have longer rides than annual members 

cycle_sum2 <- cycledata |> 
  group_by(membership) |> 
  summarise(n=n()) |> 
  mutate(percent = n*100/sum(n))

tibble(cycle_sum2) # looking at the total distribution of casual and annual members in the data

# There are more annual members than casual users of Cyclistic 

cycle_sum3 <- cycledata |> 
  group_by(membership, rideable_type) |> 
  summarise(n=n()) |> 
  mutate(percent = n*100/sum(n))

tibble(cycle_sum3) # looking at distribution of rideable type between casual and annual members 

# Electric bikes are the most popular to use by both casual and annual members
```

```{r Tableau}

# exporting the finalized data set into Tableau for visualization
write.csv(cycledata, "cycledata 2023.csv")
```


